### PR TITLE
First setup of a sphinx based documentation coupled with ReadTheDocs

### PR DESCRIPTION
**Pull request by rozsasarpi**
## Why

Except of an rst file, documentation is missing. Not only the content but the structure as well.

## What

This merge request concerns the structure, i.e. a common sphinx based documentation that is hoped to allow people to focus on writing the content in an easy and familiar manner.

* change from RST to MyST, easier to use, more similar to markdown
* examples are provided for commonly used documentation components (feel free to edit and/or even remove them)
  - automatic code documentation: `api.md` (a few examples are provided)
  - installation instructions: `installation.md`
  - references: `references.md` and `references.bib`, LaTeX like citation system
  - code examples and gallery: `examples\`
* coupling with ReadTheDocs is set up but could not be completed because I do not have sufficient rights to the repo; @aklawonn I think you will need to set this up in ReadTheDocs.

## Testing

* locally
* ReadTheDocs: to be done by someone with the right permissions

## Other

* `probeye` version number is added to `__init__.py` to store it only at one place (needed in `setup.cfg` and sphinx as well), only need to change it at one place

Related to #11

### CODE REVIEW

**Comment by rozsasarpi** [comment]
I made a fork of this repo to be able to test the coupling with ReadTheDocs. The build fails with the following error:

```
Unexpected failing examples:
/home/docs/checkouts/readthedocs.org/user_builds/probeye/checkouts/latest/docs/examples/plot_linear_regression.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/probeye/checkouts/latest/docs/examples/plot_linear_regression.py", line 83, in <module>
    problem = InferenceProblem("Linear regression with normal noise")
  File "/home/docs/checkouts/readthedocs.org/user_builds/probeye/envs/latest/lib/python3.8/site-packages/probeye/definition/inference_problem.py", line 84, in __init__
    print_probeye_header()
  File "/home/docs/checkouts/readthedocs.org/user_builds/probeye/envs/latest/lib/python3.8/site-packages/probeye/subroutines.py", line 579, in print_probeye_header
    with open(header_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/docs/checkouts/readthedocs.org/user_builds/probeye/envs/latest/lib/python3.8/site-packages/probeye/probeye.txt'
```

This seems to be an error with the logging and unrelated to the documentation.

**Comment by aklawonn** [comment]
Thanks a lot, Arpad, for setting this up! This is a big help. I have no experience with ReadTheDocs stuff, so I just changed your rights to maintain. Maybe that's already sufficient. On the error you encountered: that's weird - it seems like this probeye.txt file was not included into the build. I don't know why. Maybe it's because it's not a python-script. I don't know. If this problem also occurs for the non-forked repository, I might have to convert the txt-file into some py-file, or copy the content directly into the script that uses it (this probeye.txt file just contains the probeye name in some ascii-art font which is used at the beginning of the logging).

**Comment by rozsasarpi** [comment]
Thanks for the maintain rights. Unfortunately, I get the same error when I directly connect ReadTheDocs with this repo instead of using the fork. I also do not understand why the txt file is missing. I will try out a few things with the fork (to avoid littering this repo).

**Comment by rozsasarpi** [comment]
I can confirm that the issue is solely caused by the attempt to read `probeye.txt`. When I comment out that part of the code the documentation is built: https://probeye.readthedocs.io/en/latest/ (this built from my fork).

**Comment by aklawonn** [comment]
Great! The documentation page looks good! And I will take care of that txt-file, and simply include it in the code. I'll push that modification to this branch then.

**Comment by aklawonn** [comment]
I hope it was okay to merge your last draft into this one, Arpad. Also, you now have admin access, so there shouldn't be a rights hurdle anymore with setting up ReadTheDocs.

**Comment by TTitscher** [comment]
I had to run
~~~bash
pip3 install --user ".[docs]"
~~~
* with quotes, but that is probably related to my shell
* I was unable to run it with the "-e" editable option. Probably also a mistake on my side or do others have the same?

Anyways, `cd docs && make html` works nicely.

**Comment by rozsasarpi** [comment]
> I hope it was okay to merge your last draft into this one, Arpad. Also, you now have admin access, so there shouldn't be a rights hurdle anymore with setting up ReadTheDocs.

Sure, it is fine. I marked it as a draft because I wanted to wait until the build succeeds. It passed. The connection to ReadTheDocs is there: https://probeye.readthedocs.io/en/fix_probeye_txt/ (you can switch between branches at the bottom left, we do not build a documentation from all branches  but new branches can be added if needed).

ReadTheDocs complains about some webhooks (the build is not yet triggered automatically). I still need to figure this out (with my other repos it worked without the need to manually set this up). I will probably do some experimentation in the pull request.

**Comment by rozsasarpi** [comment]
>  Probably also a mistake on my side or do others have the same?

I tested on Windows. In the installation section of the documentation we could have one tab for Windows and another for Linux.

**Comment by rozsasarpi** [comment]
If one of you have a ReadTheDocs account, I could add you to the `probeye` project so you could also manage the builds.

**Comment by rozsasarpi** [comment]
The ReadTheDocs-GitHub webhooks are set. The documentation is automatically rebuilt and published upon each commit. Please check if something is missing from the documentation structure, otherwise, in my opinion it can be merged.

**Comment by aklawonn** [comment]
Thanks Arpad! Looks really good to me. Btw, I just made a ReadTheDocs account with the user name aklawonn. If you could add me to probeye, that would be great.

**Pull request merged**
